name: Deploy AppleJr Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  publish:
    needs: deploy
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Publish
        uses: actions/deploy-pages@v4
